#!/bin/bash

sudo pip uninstall -y time-config
sudo pip install https://github.com/andiwand/time-config/archive/master.zip

sudo pip uninstall -y time-experiments
sudo pip install https://github.com/andiwand/time-experiments/archive/master.zip
